### ISSUE TITLE
Solve message can show when it shouldn't

### ISSUE THREAD

**Issue by roice3** [roice3/MagicCube5D#1]
From a user:

> I was playing around with your magic cube 5d, attempting to solve it. I was making macros for particular tasks, and after finishing one such macro, I tested it out. After performing the macro three times on the solved cube, it would be brought back to its original, solved, state owing to the nature of the macro in question - which it did. This also, however, caused the program to believe I had just solved the cube and made a message pop up saying so, telling me I should send my log file to you, among other things. But I did not in fact solve the cube, at least not yet, as to truly solve it requires it to be solved from a fully scrambled position (of course). 
> 
> So, I thought I would notify you about this, and send my log file, so that you might be able to fix this so other people don't run into the 'solved' message when they shouldn't. (Rather spoiled a nice surprise for me, but the real surprise for me would be solving this monstrosity, so I don't really mind)

**Comment by bonimy** [comment]
The root of this error is from [cube5d.cpp:L795](https://github.com/roice3/MagicCube5D/blob/master/MagicCube5D/workFiles/cube5D.cpp#L795). The program's heuristic for showing the message is whether the cube is solved and whether over 1500 moves have occurred. The cube needs to keep an internal state variable of whether a full scramble has occurred.

**Comment by bonimy** [comment]
This should be closed now that the PR has merged.
